[package]
display_private = true
symbol = " "

[git_branch]
symbol = " "

[git_metrics]
disabled = true
added_style = "bold green"
deleted_style = "bold red"
format = '[+$added]($added_style) [-$deleted]($deleted_style) '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[directory]
truncate_to_repo = true
fish_style_pwd_dir_length = 1

[git_status]
style= "bold cyan"
ahead = "↑$count"
diverged = "↑$ahead_count↓$behind_count"
behind = "↓$count"
conflicted = " !✖$count"
untracked = " ø$count"
modified = " «$count"
up_to_date = " ✔︎ "
stashed = "❖$count| "
staged = " +$count"
renamed = "✎$count"
deleted = " ✘$count"
format = "[($stashed)](bold white)[($staged)](bold green)[($untracked)](bold yellow)[($deleted)](bold fg:160)[($conflicted)](bold fg:197)[($modified)](bold red) "